GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hydXRpIiwiaWF0IjoxNjA1NzcxMjM5LCJleHAiOjE2MDU3NzEyNjl9.Fn0lH0yEWoGyGObqYwjKgzTEeCNpAAg8X_dKmLFXrUE

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hydXRpIiwiaWF0IjoxNjA1NzcxMjAxfQ.RObHkjxVMHEjAu9nXG0xAJhjiIG3FP6aKeQz9jx81j0"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Shruti"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hydXRpIiwiaWF0IjoxNjA1NzcxMjAxfQ.RObHkjxVMHEjAu9nXG0xAJhjiIG3FP6aKeQz9jx81j0"
}